// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ReimbDBContext))]
    [Migration("20220418110017_initial M")]
    partial class initialM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataAccessLayer.Entity.ReimbursementD", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ApprovedValue")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Receipt")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("ReimburementType")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("RequestedPhase")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("RequestedValue")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.ToTable("ReimburesementDetailDb");
                });
#pragma warning restore 612, 618
        }
    }
}
